global:
  edition: ce

  hosts:
    domain: local.gitlab.com
    gitlab:
      name: local.gitlab.com
    https: false

  ingress:
    enabled: true
    class: traefik
    configureCertmanager: false
    tls:
      enabled: false

  kas:
    enabled: false

installCertmanager: false

certmanager-issuer:
  email: ankammer@student.42.fr

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1