apiVersion: apps/v1
kind: Deployment
metadata:
  name: ankammer-playground
  namespace: dev
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ankammer-playground
  template:
    metadata:
      labels:
        app: ankammer-playground
    spec:
      containers:
      - name: ankammer-playground
        image: ankammer/playground:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---

apiVersion: v1
kind: Service
metadata:
  name: ankammer-playground
  namespace: dev
spec:
  selector:
    app: ankammer-playground
  ports:
  - name: http
    protocol: TCP
    port: 8888 # port du service exposé existe seulement à l'intérieur du cluster
    targetPort: 8888 # pod ip expose le port 8888
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ankammer-playground
  namespace: dev
spec:
  ingressClassName: traefik
  rules:
  - host: local.wil.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: # dis envoi sur le service ankammer-playground sur le port 8888
            name: ankammer-playground
            port:
              number: 8888