LOGIN = "sferrad"
SERVER_NAME = "#{LOGIN}S"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.hostname = SERVER_NAME
  config.vm.network "private_network", ip: SERVER_IP
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
  end
  config.vm.provision "shell", path: "scripts/setup.sh"
  config.vm.provision "shell", path: "scripts/deploy.sh"
end